### ISSUE TITLE
utroff.org is down which means the manual is unavailable

### ISSUE THREAD

**Issue by averms** [pjfichet/utmac#1]
I would like to learn utmac for writing papers and the like but I can't find the manual. Can you upload it somewhere if getting the website back up is too hard?

**Comment by pjfichet** [comment]
Hello a-vrma,

Thank you for posting the issue! I've moved the website to <https://pjfichet.github.io/utroff>, and you'll find the documentation for utmac and related troff tools there.

If you intend using utmac only, there are manual pages in the repository: u-ref.man, utmac-hack.man and more importantly, since that's the manual to start with: utmac.man. Another source of information is the demo directory, which contains examples, and a full makefile.

Please apologize for being so long to answer: I was hesitating to rent the domain name another year, and for some reasons, I missed the notification about your issue.

Warm regards!

**Comment by averms** [comment]
Awesome, thanks!
